language: node_js
node_js:
- '10'
- '11'
- '12'
- '13'
- '14'
script:
- npm run lint
- npm run build
- npm run test:coverage
- npm run test:coveralls

jobs:
  include:
    - stage: release
      if: branch = master
      script: npx semantic-release
